### ISSUE TITLE
Identify design values

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Mofo-Design-Handbook#22] opened 2015-06-24 22:29 UTC
Let's dump ideas here and then refine...
cc @lovegushwa @sabrinang @flukeout @vazquez

**Comment by cassiemc** [comment] 2015-06-25 06:45
Duplicate of https://github.com/MozillaFoundation/Mofo-Design-Handbook/issues/28

**Closed by cassiemc** 2015-06-25 06:45 UTC
